version: '3.7'

services:
  app_python:
    image: dvechtomova/python_app:latest
    container_name: app_python
    restart: always
    user: root
    ports:
      - '8080:8080'
    healthcheck:
      test:
        - CMD-SHELL
        - wget --no-verbose --tries=1 -O /dev/null http://localhost:8080/healthcheck || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - app_python_visits:/app/volume/

  app_rust:
    image: dvechtomova/rust_app:latest
    container_name: app_rust
    restart: always
    user: root
    ports:
      - '8081:8080'
    healthcheck:
      test:
        - CMD-SHELL
        - wget --no-verbose --tries=1 -O /dev/null http://localhost:8080/healthcheck || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - app_rust_visits:/app/volume/

volumes:
  app_python_visits:
  app_rust_visits:
